/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGovDataReference,
  IGovDataReferenceInterface,
} from "../../interfaces/IGovDataReference";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_idImob",
        type: "uint256",
      },
    ],
    name: "ConsultImobReg",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_registryRural",
        type: "uint256",
      },
    ],
    name: "ConsultMapRural",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "_map",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "_registryRural",
        type: "uint256",
      },
    ],
    name: "confrontMapEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_idImob",
        type: "uint256",
      },
    ],
    name: "ConsultRegular",
    outputs: [
      {
        internalType: "bool",
        name: "regular",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_map",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_registryRural",
        type: "uint256",
      },
    ],
    name: "confrontMap",
    outputs: [
      {
        internalType: "bool",
        name: "regular",
        type: "bool",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_registryRural",
        type: "uint256",
      },
    ],
    name: "consultMap",
    outputs: [
      {
        internalType: "bool",
        name: "regular",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGovDataReference__factory {
  static readonly abi = _abi;
  static createInterface(): IGovDataReferenceInterface {
    return new utils.Interface(_abi) as IGovDataReferenceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGovDataReference {
    return new Contract(address, _abi, signerOrProvider) as IGovDataReference;
  }
}
