/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ConsultImobInterface extends utils.Interface {
  functions: {
    "confrontMap(string,uint256)": FunctionFragment;
    "consultMap(uint256)": FunctionFragment;
    "consultRegular(uint256)": FunctionFragment;
    "govData()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "confrontMap"
      | "consultMap"
      | "consultRegular"
      | "govData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confrontMap",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "consultMap",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "consultRegular",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "govData", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "confrontMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consultMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "consultRegular",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "govData", data: BytesLike): Result;

  events: {};
}

export interface ConsultImob extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConsultImobInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRual: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    consultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    govData(overrides?: CallOverrides): Promise<[string]>;
  };

  confrontMap(
    _map: PromiseOrValue<string>,
    _registryRual: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  consultMap(
    _registryRural: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  consultRegular(
    _idImob: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  govData(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRual: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    consultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    govData(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRual: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    govData(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRual: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    consultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    govData(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
