/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockImob } from "./IBlockImob";
export type { IERC20 } from "./IERC20";
export type { IERC4907 } from "./IERC4907";
export type { IGovDataReference } from "./IGovDataReference";
