/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface OracleGovInterface extends utils.Interface {
  functions: {
    "ConsultRegular(uint256)": FunctionFragment;
    "confrontMap(string,uint256)": FunctionFragment;
    "consultMap(uint256)": FunctionFragment;
    "numberImobRegular()": FunctionFragment;
    "numberMapRegularRural()": FunctionFragment;
    "setAllow(address,bool)": FunctionFragment;
    "setMapRural(string)": FunctionFragment;
    "setRegular(uint256,bool,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ConsultRegular"
      | "confrontMap"
      | "consultMap"
      | "numberImobRegular"
      | "numberMapRegularRural"
      | "setAllow"
      | "setMapRural"
      | "setRegular"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ConsultRegular",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "confrontMap",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "consultMap",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "numberImobRegular",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numberMapRegularRural",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAllow",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMapRural",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegular",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "ConsultRegular",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confrontMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consultMap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numberImobRegular",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "numberMapRegularRural",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAllow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMapRural",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRegular", data: BytesLike): Result;

  events: {
    "ConsultImobReg(uint256)": EventFragment;
    "ConsultMapRural(uint256)": EventFragment;
    "confrontMapEvent(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ConsultImobReg"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConsultMapRural"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "confrontMapEvent"): EventFragment;
}

export interface ConsultImobRegEventObject {
  _idImob: BigNumber;
}
export type ConsultImobRegEvent = TypedEvent<
  [BigNumber],
  ConsultImobRegEventObject
>;

export type ConsultImobRegEventFilter = TypedEventFilter<ConsultImobRegEvent>;

export interface ConsultMapRuralEventObject {
  _registryRural: BigNumber;
}
export type ConsultMapRuralEvent = TypedEvent<
  [BigNumber],
  ConsultMapRuralEventObject
>;

export type ConsultMapRuralEventFilter = TypedEventFilter<ConsultMapRuralEvent>;

export interface confrontMapEventEventObject {
  _map: string;
  _registryRural: BigNumber;
}
export type confrontMapEventEvent = TypedEvent<
  [string, BigNumber],
  confrontMapEventEventObject
>;

export type confrontMapEventEventFilter =
  TypedEventFilter<confrontMapEventEvent>;

export interface OracleGov extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OracleGovInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ConsultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { regular: boolean }>;

    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { regular: boolean }>;

    numberImobRegular(overrides?: CallOverrides): Promise<[BigNumber]>;

    numberMapRegularRural(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAllow(
      _addr: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMapRural(
      _maprural: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      _regular: PromiseOrValue<boolean>,
      _imobcontract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  ConsultRegular(
    _idImob: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  confrontMap(
    _map: PromiseOrValue<string>,
    _registryRural: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  consultMap(
    _registryRural: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numberImobRegular(overrides?: CallOverrides): Promise<BigNumber>;

  numberMapRegularRural(overrides?: CallOverrides): Promise<BigNumber>;

  setAllow(
    _addr: PromiseOrValue<string>,
    _allow: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMapRural(
    _maprural: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRegular(
    _idImob: PromiseOrValue<BigNumberish>,
    _regular: PromiseOrValue<boolean>,
    _imobcontract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ConsultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean, string]>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numberImobRegular(overrides?: CallOverrides): Promise<BigNumber>;

    numberMapRegularRural(overrides?: CallOverrides): Promise<BigNumber>;

    setAllow(
      _addr: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMapRural(
      _maprural: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      _regular: PromiseOrValue<boolean>,
      _imobcontract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ConsultImobReg(uint256)"(
      _idImob?: PromiseOrValue<BigNumberish> | null
    ): ConsultImobRegEventFilter;
    ConsultImobReg(
      _idImob?: PromiseOrValue<BigNumberish> | null
    ): ConsultImobRegEventFilter;

    "ConsultMapRural(uint256)"(
      _registryRural?: PromiseOrValue<BigNumberish> | null
    ): ConsultMapRuralEventFilter;
    ConsultMapRural(
      _registryRural?: PromiseOrValue<BigNumberish> | null
    ): ConsultMapRuralEventFilter;

    "confrontMapEvent(string,uint256)"(
      _map?: null,
      _registryRural?: PromiseOrValue<BigNumberish> | null
    ): confrontMapEventEventFilter;
    confrontMapEvent(
      _map?: null,
      _registryRural?: PromiseOrValue<BigNumberish> | null
    ): confrontMapEventEventFilter;
  };

  estimateGas: {
    ConsultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numberImobRegular(overrides?: CallOverrides): Promise<BigNumber>;

    numberMapRegularRural(overrides?: CallOverrides): Promise<BigNumber>;

    setAllow(
      _addr: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMapRural(
      _maprural: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      _regular: PromiseOrValue<boolean>,
      _imobcontract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ConsultRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confrontMap(
      _map: PromiseOrValue<string>,
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    consultMap(
      _registryRural: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numberImobRegular(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numberMapRegularRural(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAllow(
      _addr: PromiseOrValue<string>,
      _allow: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMapRural(
      _maprural: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRegular(
      _idImob: PromiseOrValue<BigNumberish>,
      _regular: PromiseOrValue<boolean>,
      _imobcontract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
