/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBlockImob__factory } from "./IBlockImob__factory";
export { IERC20__factory } from "./IERC20__factory";
export { IERC4907__factory } from "./IERC4907__factory";
export { IGovDataReference__factory } from "./IGovDataReference__factory";
